<template>
  <figure class="overlay-diagram" aria-label="An ORD Overlay enriches a resource definition without modifying the source">
    <div class="flow">
      <section class="artifact source">
        <span class="kind">Source definition</span>
        <strong>openapi.json</strong>
        <code><i>operationId</i>: listOrders<br><i>summary</i>: List orders</code>
        <small>Owned and generated by the API team</small>
      </section>

      <div class="operator"><b>+</b><span>apply</span></div>

      <section class="artifact overlay">
        <span class="kind">ORD Overlay 0.1 · beta</span>
        <strong>orders.overlay.json</strong>
        <code><i>action</i>: merge<br><i>selector</i>: {<br>&nbsp; <i>operation</i>: listOrders<br>}<br><i>data</i>: { summary: … }</code>
        <small>Separately owned, versioned, and governed</small>
      </section>

      <div class="operator"><b>=</b><span>merge</span></div>

      <section class="artifact result">
        <span class="kind">Enriched definition</span>
        <strong>OpenAPI + guidance</strong>
        <code><i>operationId</i>: listOrders<br><i>summary</i>: List orders<br>for fulfillment<br><i>description</i>: …</code>
        <small>Original contract remains unchanged</small>
      </section>
    </div>

    <figcaption>
      <span><b>Target</b> ORD ID + definition type or URL</span>
      <span><b>Select</b> operation, entity, property, root, or JSONPath</span>
      <span><b>Patch</b> merge, update, or remove</span>
      <a href="https://open-resource-discovery.org/spec-v1/interfaces/OrdOverlay" target="_blank" rel="noreferrer">ORD Overlay specification ↗</a>
    </figcaption>
  </figure>
</template>

<style scoped>
.overlay-diagram { display: flex; flex: 1; min-height: 0; flex-direction: column; justify-content: center; gap: 18px; margin: 0; }
.flow { display: grid; grid-template-columns: 1fr 62px 1fr 62px 1fr; align-items: stretch; }
.artifact { display: flex; min-width: 0; min-height: 280px; flex-direction: column; gap: 12px; border: 1px solid var(--ord-border); border-radius: var(--ord-radius); background: var(--ord-card-bg); padding: 22px; }
.artifact.overlay { border: 2px solid var(--ord-brand-2); background: var(--ord-teal-soft); }
.artifact.result { border-color: var(--ord-brand); background: linear-gradient(145deg, var(--ord-card-bg), var(--ord-sky-soft)); }
.kind { color: var(--ord-brand); font-size: 14px; font-weight: 750; }
.artifact strong { color: var(--ord-text); font-size: 19px; }
.artifact code { display: block; flex: 1; border-radius: 6px; background: #141a21; color: #d4d4d4; font-family: var(--ord-mono); font-size: 16px; line-height: 1.55; padding: 15px; overflow-wrap: anywhere; }
.artifact code i { color: #9cdcfe; font-style: normal; }
.artifact small { color: var(--ord-muted); font-size: 16px; line-height: 1.35; }
.operator { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 5px; color: var(--ord-muted); }
.operator b { color: var(--ord-brand); font-size: 32px; font-weight: 450; }
.operator span { font-size: 10px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; }
figcaption { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; align-items: center; border: 1px solid var(--ord-sep); border-radius: var(--ord-radius); background: var(--ord-panel-soft); padding: 13px 16px; }
figcaption span { color: var(--ord-muted); font-size: 16px; }
figcaption b { color: var(--ord-text); }
figcaption a { grid-column: 1 / -1; justify-self: end; color: var(--ord-brand); font-size: 16px; font-weight: 700; text-decoration: none; white-space: nowrap; }
</style>
